apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: admin-service
  ports:
    - port: {{ .Values.ports.admin }}
      targetPort: {{ .Values.ports.admin }}
  type: ClusterIP
