apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: chat-service
  ports:
    - port: {{ .Values.ports.chat }}
      targetPort: {{ .Values.ports.chat }}
  type: ClusterIP
