apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: streaming-service
  ports:
    - port: {{ .Values.ports.streaming }}
      targetPort: {{ .Values.ports.streaming }}
  type: ClusterIP
