apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
  namespace: streamingapp
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongodb:27017/streamingapp"
  CLIENT_URLS: "*"
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET: "streamingapp-627917841032-ap-south-1"
  AWS_CDN_URL: ""
  STREAMING_PUBLIC_URL: "/"
  AUTH_PORT: "3001"
  STREAMING_PORT: "3002"
  ADMIN_PORT: "3003"
  CHAT_PORT: "3004"